mvidner/ruby-dbus

lib/dbus/bus.rb

FreeBSD uses `/var/db/dbus`, not `/var/lib/dbus`

Fix default path finding on FreeBSD

---

lib/dbus/bus.rb
spec/session_bus_spec.rb

Hi :-D
I've got following error after update of **dbus** (system dbus, not ruby-dbus)
```zsh
% bundle exec ruby -e 'require "dbus"; DBus::SessionBus.instance'               
/path/to/gems/ruby/2.3.0/gems/ruby-dbus-0.11.1/lib/dbus/message_queue.rb:46:in `push': undefined method `write' for nil:NilClass (NoMethodError)
from /path/to/gems/ruby/2.3.0/gems/ruby-dbus-0.11.1/lib/dbus/bus.rb:442:in `send_sync'
from /path/to/gems/ruby/2.3.0/gems/ruby-dbus-0.11.1/lib/dbus/bus.rb:582:in `send_hello'
from /path/to/gems/ruby/2.3.0/gems/ruby-dbus-0.11.1/lib/dbus/bus.rb:601:in `initialize'        from /path/to/ruby/2.3.0/singleton.rb:142:in `new'                      
from /path/to/ruby/2.3.0/singleton.rb:142:in `block in instance'        
from /path/to/ruby/2.3.0/singleton.rb:140:in `synchronize' …
```

Improve DBUS_SESSION_BUS_ADDRESS extraction

---

README.md

- The main GitHub page displayed "failing" Travis status, but it turned out it's not for the "master" but for some [failed pull request](https://travis-ci.org/mvidner/ruby-dbus/builds/358386341) and the "master" branch build passed correctly.
- Use the "master" branch instead of the latest build (in any branch)

Fixed Travis badge in README.md

---

lib/dbus/core_ext/class/attribute.rb
lib/dbus/object.rb

`require_relative` is not used everywhere and prevent using this lib with `require_relative`.

Change require to require_relative

---

examples/service/call_service.rb

The diff should be self explanatory. Hopefully this is uncontroversial, but this seemed unnecessarily and surprisingly sexual as I was looking for some code examples for `ruby-dbus`. :bowing_man:

Replace unnecessarily sexual example

---

ruby-dbus.gemspec

ruby-dbus make crash on load in ruby 3.0.0 .
```
/home/toshi/Project/mikutter/vendor/bundle/mikutter-cli/ruby/3.0.0/gems/ruby-dbus-0.16.0/lib/dbus/xml.rb:13:in `require': cannot load such file -- rexml/document (LoadError)
from /home/toshi/Project/mikutter/vendor/bundle/mikutter-cli/ruby/3.0.0/gems/ruby-dbus-0.16.0/lib/dbus/xml.rb:13:in `<top (required)>'
```
In ruby 3, rexml becomes bundled gem.
I think ruby-dbus should make dependency to 'rexml'.
see: https://github.com/rails/rails/pull/40281

Make dependency to rexml

---

.github/workflows/ruby.yml
.gitignore
.rubocop.yml
HOWTO-RELEASE
README.md
Rakefile
lib/dbus/proxy_object.rb
ruby-dbus.gemspec
spec/spec_helper.rb
spec/tools/dbus-limited-session.conf

Travis-CI.ORG is no longer working: https://blog.travis-ci.com/2021-05-07-orgshutdown
**Ruby versions**
- must succeed on currently maintained Rubies: 2.6 to 3.1
- must succeed on 2.5, unmaintained upstream, but included in SLE15
- can fail on `head` Ruby 
- (not caring about 2.1 to 2.4 which were enabled in Travis.)
Code coverage reporting on **Coveralls** works again: https://coveralls.io/github/mvidner/ruby-dbus
(coveralls.gem no longer needed for that)
**Rubocop**: for now disabled on Ruby 3.x until I update the config (and code), see Issue #94

CI with GitHub Actions

---

NEWS.md
doc/Reference.md
lib/dbus/marshall.rb
lib/dbus/object.rb
spec/property_spec.rb
spec/service_newapi.rb
spec/value_spec.rb

Responding to #97.
Before this PR, the return signature for getting a property was a Variant:
> org.freedesktop.DBus.Properties.Get(..., ..., out **VARIANT** value)
With no type hint for the Ruby -> D-Bus data conversion, a property with a nontrivial type, such as STRUCT, would get returned incorrectly:
```console
$ busctl --user --list introspect org.ruby.service /org/ruby/MyInstance | grep -E NAME\|MyStruct
NAME                            TYPE      SIGNATURE RESULT/VALUE                            FLAGS
.MyStruct                       property  (sss)     3 s "three" s "strings" s "in a struct" emits-change # not visible here
$ dbus-send --session --print-reply --dest=org.ruby.service /org/ruby/MyInstance org.freedesktop.DBus.Properties.Get string:org.ruby.SampleInterface string:MyStruct …
```

Improve D-Bus struct handling: as properties

---

NEWS.md
doc/Reference.md
lib/dbus/marshall.rb
lib/dbus/type.rb
spec/type_spec.rb

This is a subtask of #103 but it is separate enough to make sense as a standalone PR.
Previously it was easy to construct an invalid signature, even for trivially bad cases.
Now, make sure `DBus.type` constructs a valid Single Complete Type, and add `DBus.types` for constructing a valid Signature (0 or more SCTs)
Add test cases.
The corresponding section of the specification is [Type System](https://dbus.freedesktop.org/doc/dbus-specification.html#type-system)
Also, `DBus::Type` was an internal Module and the constructed Class was awkwardly named `DBus::Type::Type`. Merged them (with a compatibility "symlink")

Make sure DBus.type constructs a valid one

---

lib/dbus/data.rb
lib/dbus/marshall.rb
spec/data_spec.rb
spec/property_spec.rb
spec/service_newapi.rb

For issue see https://github.com/yast/d-installer/issues/126
(mvidner: As suspected, the container typed properties were indeed incomplete in #103, and the only thing that worked was Struct. Fixing Array, Dict, and Variant now.)

Fix returning container-typed properties

---

NEWS.md
lib/dbus/marshall.rb
spec/packet_marshaller_spec.rb

A fix for https://github.com/yast/d-installer/issues/126#issuecomment-1101223422
CLI test:
```console
busctl get-property org.opensuse.DInstaller /org/opensuse/DInstaller/Language1 org.opensuse.DInstaller.Language1 AvailableLanguages
```
The existing tests would only catch it if `my_array` was a *nested* array, such as `aaq`

Fix forgotten case: marshall Data::Array as an ARRAY

---

NEWS.md
doc/Reference.md
lib/dbus/data.rb
lib/dbus/introspect.rb
lib/dbus/proxy_object_factory.rb
lib/dbus/proxy_object_interface.rb
lib/dbus/type.rb
lib/dbus/xml.rb
spec/data_spec.rb
spec/property_spec.rb
spec/service_newapi.rb

The type has always been VARIANT, as required by the method signature, but the type wrapped *inside* was guessed poorly, by
`PacketMarshaller.make_variant`.
Fix it by converting the supplied argument with `Data.make_typed`, using the property type learned by introspection.
Added `ProxyObjectInterface#properties` which were missing until now.

When calling Properties.Set in ProxyObjectInterface#[]=, use correct type (#108)

---

NEWS.md
lib/dbus/object.rb
lib/dbus/type.rb
spec/object_spec.rb
spec/property_spec.rb
spec/service_newapi.rb

Use the correct type for values in PropertiesChanged 

---

.github/workflows/ruby.yml
NEWS.md
examples/simple/get_id.rb
lib/dbus/auth.rb
lib/dbus/message_queue.rb
spec/auth_spec.rb
spec/spec_helper.rb
spec/tools/dbus-limited-session.conf

Authenticating across containers, like `busctl` can do, should work now (#126).
To be able to do that, I had to understand the protocol, which had been a messy black box for me.
Added tests, covering almost all of `auth.rb` (leaving out the parts that I want to replace/fix next).
When reviewing, the `auth.rb` diff is almost meaningless, even when ignoring whitespace, and I suggest to just read the nev version.

Authentication: allow authentication with containers; refactor and test it all.

---

NEWS.md
lib/dbus/message_queue.rb
spec/thread_safety_spec.rb

Triggered by https://github.com/yast/d-installer/pull/476
The previous attempt at thread safety failed (https://github.com/mvidner/ruby-dbus/issues/7, https://github.com/mvidner/ruby-dbus/issues/73) but now I see a limited use case:
A worker thread only uses the shared bus connection to send signals about its progress and completion. No method calls are accepted there.
That is, we only race for the bus connection in MessageQueue#push, not in the #pop reading part.

Signal thread safety: Add a mutex to MessageQueue#push,pop

---

NEWS.md
lib/dbus/message_queue.rb

Some services call dispatch_message_queue (nonblocking) a lot and memory_profiler.gem shows many string allocations in the socket library.
Preallocating our own buffer helps with that.

Reduce socket buffer allocations

---

NEWS.md
lib/dbus.rb
lib/dbus/message.rb
spec/raw_message_spec.rb

also:  Message#marshall speedup: don't marshall the body twice.

Respect env RUBY_DBUS_ENDIANNESS=B (or =l) for outgoing messages.

---

NEWS.md
spec/tools/dbus-limited-session.conf

it does not work in openSUSE Build Service
https://build.opensuse.org/package/live_build_log/devel:languages:ruby:extensions/rubygem-ruby-dbus/openSUSE_Tumbleweed/x86_64
> [   19s] ~/rpmbuild/BUILDROOT/rubygem-ruby-dbus-0.22.0-50.1.x86_64/usr/lib64/ruby/gems/3.2.0/gems/ruby-dbus-0.22.0 ~/rpmbuild/BUILD
> [   19s] + rake test
> [   19s] ./test_env rake bare:spec
> [   19s] cd spec/tools
> [   19s] dbus-daemon[1904]: Failed to start message bus: Failed to lookup host/port: "::1:0": Name or service not known (-2)
> [   29s] dbus-daemon failed?
>

Disable IPv6 test again

---

NEWS.md
examples/utils/listnames.rb
lib/dbus/bus.rb
lib/dbus/connection.rb
spec/bus_connection_spec.rb

tuned the API and its docs so that the simple use is easy and complex things are possible

BusConnection#request_name defaults to the simple use case

---

lib/dbus/proxy_object.rb
spec/signal_spec.rb

ruby 3.4 changes backtrace formatting, including
opening quote using single quote instead of backtick.
Make DBus::ProxyObject support both backtrace format.
Fixes #144 .

Support ruby 3.4 backtrace formatting change
